wisepaas:
  nodeId: f73bccb7-9f8f-43f0-9885-fa8bb4007cec
  deviceId: 6lQguETNe7sT
  dccs:
    apiUrl: https://api-dccs-ensaas.sa.wise-paas.com/
    credentialKey: ce1d18d989864138e1d55203fd80f32m
  edgeTag:
    count: 5
    tag1: Inlet_flow
    tag2: Outlet_flow
    tag3: Current
    tag4: Volt
    tag5: Power
modbus:
  host: 192.168.227.128
  port: 502
