wisepaas:
  nodeId: f73bccb7-9f8f-43f0-9885-fa8bb4007cec
  deviceId: 6lQguETNe7sT
  dccs:
    apiUrl: https://api-dccs-ensaas.sa.wise-paas.com/
    credentialKey: ce1d18d989864138e1d55203fd80f32m
  edgeTag:
    count: 5
    tag1: a
    tag2: b
    tag3: c
    tag4: d
    tag5: e
modbus:
  host: 172.20.10.8
  port: 502
