wisepaas:
  nodeId: f1ab63c1-c5de-409b-ba21-a3ef217fbe23
  deviceId: 5YmxqCcmCAHR
  dccs:
    apiUrl: https://api-dccs-ensaas.education.wise-paas.com/
    credentialKey: cb9fa814124422470e5089a9a3b586mz
  edgeTag:
    count: 5
    tag1: Inlet_flow
    tag2: Outlet_flow
    tag3: Current
    tag4: a
    tag5: Power
modbus:
  host: 192.168.227.128
  port: 502
serial:
  port: /dev/ttyACM0
  baudrate: 9600
serial2:
  port: /dev/ttyACM1
  baudrate: 9600
